name: Test Cypress 👀

on: pull_request

env:
  STRAPI_GRAPHQL_ENDPOINT: ${{ secrets.STRAPI_GRAPHQL_ENDPOINT }}
  NEXT_PUBLIC_STRAPI_BEARER_TOKEN: ${{ secrets.NEXT_PUBLIC_STRAPI_BEARER_TOKEN }}
  NEXT_PUBLIC_STRAPI_GRAPHQL_ENDPOINT: ${{ secrets.NEXT_PUBLIC_STRAPI_GRAPHQL_ENDPOINT }}

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          browser: chrome
